// Package recipe provides built-in prompt library scaffolding for common stacks.
package recipe

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/sayandeep14/PromptLoom/internal/config"
)

// File is one file to be generated by a recipe.
type File struct {
	RelPath  string // relative to project root, e.g. "prompts/Foo.prompt.loom"
	Template string // content with {{Key}} placeholders
}

// Recipe is a named scaffolding template.
type Recipe struct {
	Name        string
	Description string
	Flags       []string // supported flags, e.g. "--language", "--framework"
	Files       []File
}

// Options carries the flag values passed to `loom recipe apply`.
type Options struct {
	Language  string
	Framework string
	Style     string // for api-designer: rest|graphql
}

// ApplyResult describes what was generated.
type ApplyResult struct {
	Written []string
	Skipped []string
}

var catalog = []Recipe{
	recipeReviewer,
	recipeAPIDesigner,
	recipeMigrationAssistant,
	recipeSecurityAuditor,
	recipeDocsWriter,
}

// List returns all built-in recipes.
func List() []Recipe { return catalog }

// Get returns a recipe by name (case-insensitive). ok is false if not found.
func Get(name string) (Recipe, bool) {
	for _, r := range catalog {
		if strings.EqualFold(r.Name, name) {
			return r, true
		}
	}
	return Recipe{}, false
}

// Apply generates the recipe files into the project at cwd.
// Existing files are skipped unless force is true.
func Apply(name string, opts Options, cwd string, force bool) (ApplyResult, error) {
	r, ok := Get(name)
	if !ok {
		return ApplyResult{}, fmt.Errorf("recipe %q not found — run `loom recipe list` to see available recipes", name)
	}

	vars := buildVars(opts)
	var result ApplyResult
	dirs := sourceDirs(cwd)

	for _, f := range r.Files {
		rel := mapDir(substitute(f.RelPath, vars), dirs)
		abs := filepath.Join(cwd, rel)

		if _, err := os.Stat(abs); err == nil && !force {
			result.Skipped = append(result.Skipped, rel)
			continue
		}

		content := substitute(f.Template, vars)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return result, fmt.Errorf("create dir for %s: %w", rel, err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			return result, fmt.Errorf("write %s: %w", rel, err)
		}
		result.Written = append(result.Written, rel)
	}
	return result, nil
}

// sourceDirs returns where prompts, blocks and overlays live in the project at cwd: the
// [paths] of loom.toml, or the plain defaults when there is no (readable) config.
func sourceDirs(cwd string) map[string]string {
	dirs := map[string]string{"prompts": "prompts", "blocks": "blocks", "overlays": "overlays"}
	if cfg, err := config.Load(cwd); err == nil {
		for kind, dir := range map[string]string{"prompts": cfg.Paths.Prompts, "blocks": cfg.Paths.Blocks, "overlays": cfg.Paths.Overlays} {
			if dir != "" {
				dirs[kind] = dir
			}
		}
	}
	return dirs
}

// mapDir rewrites the leading "prompts/", "blocks/" or "overlays/" of a template path to the
// project's configured directory, so recipes land where `loom inspect` looks for them.
func mapDir(rel string, dirs map[string]string) string {
	kind, rest, ok := strings.Cut(rel, "/")
	if !ok {
		return rel
	}
	if dir, ok := dirs[kind]; ok {
		return filepath.ToSlash(filepath.Join(dir, rest))
	}
	return rel
}

// buildVars builds the substitution map from options.
//
// Values are inserted into DSL source and into file names, so they are cleaned first: the
// display forms ({{Language}}, {{Framework}}, ...) are collapsed to a single line, and the
// name forms ({{LangPascal}}, {{FwPascal}}) keep only letters and digits, which makes them
// valid in a prompt name and in a path.
func buildVars(opts Options) map[string]string {
	lang := oneLine(opts.Language)
	if lang == "" {
		lang = "Generic"
	}
	fw := oneLine(opts.Framework)
	style := oneLine(opts.Style)
	if style == "" {
		style = "rest"
	}

	pascal := toPascal(lang)
	fwPascal := toPascal(fw)
	fwTitle := titleCase(strings.ReplaceAll(fw, "-", " "))

	return map[string]string{
		"{{Language}}":       lang,
		"{{language}}":       strings.ToLower(lang),
		"{{LangPascal}}":     pascal,
		"{{Framework}}":      fw,
		"{{framework}}":      strings.ToLower(fw),
		"{{FwPascal}}":       fwPascal,
		"{{FrameworkTitle}}": fwTitle,
		"{{Style}}":          style,
		"{{style}}":          strings.ToLower(style),
	}
}

// oneLine collapses all whitespace (including newlines) to single spaces, drops other control
// characters and caps the length, so a value can never add lines to the generated DSL.
func oneLine(s string) string {
	s = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) && !unicode.IsSpace(r) {
			return -1
		}
		return r
	}, s)
	s = strings.Join(strings.Fields(s), " ")
	if r := []rune(s); len(r) > 60 {
		s = string(r[:60])
	}
	return s
}

// substitute replaces every {{Key}} in one pass: a value that itself contains a placeholder is
// inserted literally, and the result does not depend on map iteration order.
func substitute(s string, vars map[string]string) string {
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	pairs := make([]string, 0, 2*len(keys))
	for _, k := range keys {
		pairs = append(pairs, k, vars[k])
	}
	return strings.NewReplacer(pairs...).Replace(s)
}

func titleCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		if r := []rune(w); len(r) > 0 {
			words[i] = string(unicode.ToUpper(r[0])) + string(r[1:])
		}
	}
	return strings.Join(words, " ")
}

// toPascal joins the letters and digits of s into PascalCase. Everything else (spaces, dashes,
// dots, slashes, symbols) only separates words and is dropped.
func toPascal(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case !unicode.IsLetter(r) && !unicode.IsDigit(r):
			upper = true
		case upper:
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
