// Package recipe provides built-in prompt library scaffolding for common stacks.
package recipe

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// File is one file to be generated by a recipe.
type File struct {
	RelPath  string // relative to project root, e.g. "prompts/Foo.prompt.loom"
	Template string // content with {{Key}} placeholders
}

// Recipe is a named scaffolding template.
type Recipe struct {
	Name        string
	Description string
	Flags       []string // supported flags, e.g. "--language", "--framework"
	Files       []File
}

// Options carries the flag values passed to `loom recipe apply`.
type Options struct {
	Language  string
	Framework string
	Style     string // for api-designer: rest|graphql
}

// ApplyResult describes what was generated.
type ApplyResult struct {
	Written []string
	Skipped []string
}

var catalog = []Recipe{
	recipeReviewer,
	recipeAPIDesigner,
	recipeMigrationAssistant,
	recipeSecurityAuditor,
	recipeDocsWriter,
}

// List returns all built-in recipes.
func List() []Recipe { return catalog }

// Get returns a recipe by name (case-insensitive). ok is false if not found.
func Get(name string) (Recipe, bool) {
	for _, r := range catalog {
		if strings.EqualFold(r.Name, name) {
			return r, true
		}
	}
	return Recipe{}, false
}

// Apply generates the recipe files into the project at cwd.
// Existing files are skipped unless force is true.
func Apply(name string, opts Options, cwd string, force bool) (ApplyResult, error) {
	r, ok := Get(name)
	if !ok {
		return ApplyResult{}, fmt.Errorf("recipe %q not found — run `loom recipe list` to see available recipes", name)
	}

	vars := buildVars(opts)
	var result ApplyResult

	for _, f := range r.Files {
		rel := substitute(f.RelPath, vars)
		abs := filepath.Join(cwd, rel)

		if _, err := os.Stat(abs); err == nil && !force {
			result.Skipped = append(result.Skipped, rel)
			continue
		}

		content := substitute(f.Template, vars)
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return result, fmt.Errorf("create dir for %s: %w", rel, err)
		}
		if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
			return result, fmt.Errorf("write %s: %w", rel, err)
		}
		result.Written = append(result.Written, rel)
	}
	return result, nil
}

// buildVars builds the substitution map from options.
func buildVars(opts Options) map[string]string {
	lang := opts.Language
	if lang == "" {
		lang = "Generic"
	}
	fw := opts.Framework
	if fw == "" {
		fw = ""
	}
	style := opts.Style
	if style == "" {
		style = "rest"
	}

	pascal := toPascal(lang)
	fwPascal := toPascal(fw)
	fwTitle := titleCase(strings.ReplaceAll(fw, "-", " "))

	return map[string]string{
		"{{Language}}":      lang,
		"{{language}}":      strings.ToLower(lang),
		"{{LangPascal}}":    pascal,
		"{{Framework}}":     fw,
		"{{framework}}":     strings.ToLower(fw),
		"{{FwPascal}}":      fwPascal,
		"{{FrameworkTitle}}": fwTitle,
		"{{Style}}":         style,
		"{{style}}":         strings.ToLower(style),
	}
}

func substitute(s string, vars map[string]string) string {
	for k, v := range vars {
		s = strings.ReplaceAll(s, k, v)
	}
	return s
}

func titleCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

func toPascal(s string) string {
	if s == "" {
		return ""
	}
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case r == '-' || r == '_' || r == ' ':
			upper = true
		case upper:
			if r >= 'a' && r <= 'z' {
				b.WriteRune(r - 32)
			} else {
				b.WriteRune(r)
			}
			upper = false
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}
